#!/bin/bash

OWS_DIR="/data/lapig-maps/prod/ows/"
NODE_DIR="/home/lapig-server/.nvm/v0.12.2"
LOG_FILE="/var/log/lapig-maps/ows.log"
USER="lapig-server"

cd $OWS_DIR
su -m -c "export NODE_ENV=prod; $NODE_DIR/bin/node app-cluster.js" $USER