#!/bin/bash

SERVER_DIR="/data/lapig-maps/prod/server/"
NODE_DIR="/home/lapig-server/.nvm/v0.10.25"
LOG_FILE="/var/log/lapig-maps/server.log"
USER="lapig-server"

cd $SERVER_DIR
su -m -c "export NODE_ENV=prod; $NODE_DIR/bin/node app-cluster.js" $USER